//! Domain model + seed-data loaders. The catalog and orders are the single
//! source of truth the tools read from — nothing is generated by the LLM.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::Path;

use crate::util::normaliza;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Variant {
    pub sku: String,
    pub color: String,
    #[serde(default)]
    pub talla: Option<String>,
    pub stock: u32,
    #[serde(default)]
    pub precio_mxn: Option<u32>,
    #[serde(default)]
    pub foto_url: Vec<String>,
}

impl Variant {
    pub fn disponible(&self) -> bool {
        self.stock > 0
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Product {
    pub sku: String,
    pub nombre_es: String,
    pub categoria: String,
    pub precio_mxn: u32,
    pub descripcion_es: String,
    #[serde(default)]
    pub foto_url: Vec<String>,
    #[serde(default)]
    pub politica_devolucion: Option<String>,
    pub variantes: Vec<Variant>,
}

impl Product {
    /// Effective unit price for a variant (variant override or product price).
    pub fn precio_de(&self, v: &Variant) -> u32 {
        v.precio_mxn.unwrap_or(self.precio_mxn)
    }

    pub fn stock_total(&self) -> u32 {
        self.variantes.iter().map(|v| v.stock).sum()
    }

    pub fn colores(&self) -> Vec<String> {
        unicos(self.variantes.iter().map(|v| v.color.clone()))
    }

    pub fn tallas(&self) -> Vec<String> {
        unicos(self.variantes.iter().filter_map(|v| v.talla.clone()))
    }

    pub fn find_variant(&self, sku: &str) -> Option<&Variant> {
        self.variantes
            .iter()
            .find(|v| v.sku.eq_ignore_ascii_case(sku))
    }

    /// Photos for a variant, falling back to the product-level photos.
    pub fn fotos_de(&self, v: &Variant) -> Vec<String> {
        if v.foto_url.is_empty() {
            self.foto_url.clone()
        } else {
            v.foto_url.clone()
        }
    }
}

fn unicos<I: IntoIterator<Item = String>>(it: I) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for x in it {
        if !out.iter().any(|e| e == &x) {
            out.push(x);
        }
    }
    out
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EstadoPedido {
    Pendiente,
    Pagado,
    EnCamino,
    Entregado,
    Cancelado,
    Devuelto,
}

impl EstadoPedido {
    pub fn legible(&self) -> &'static str {
        match self {
            EstadoPedido::Pendiente => "pendiente de pago",
            EstadoPedido::Pagado => "pagado, preparando envío",
            EstadoPedido::EnCamino => "en camino",
            EstadoPedido::Entregado => "entregado",
            EstadoPedido::Cancelado => "cancelado",
            EstadoPedido::Devuelto => "devuelto",
        }
    }

    /// snake_case wire form ("en_camino"), useful for JSON tool results.
    pub fn slug(&self) -> &'static str {
        match self {
            EstadoPedido::Pendiente => "pendiente",
            EstadoPedido::Pagado => "pagado",
            EstadoPedido::EnCamino => "en_camino",
            EstadoPedido::Entregado => "entregado",
            EstadoPedido::Cancelado => "cancelado",
            EstadoPedido::Devuelto => "devuelto",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderItem {
    pub sku: String,
    pub nombre_es: String,
    pub qty: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Order {
    pub order_id: String,
    pub cliente: String,
    pub estado: EstadoPedido,
    pub items: Vec<OrderItem>,
    pub fecha_pedido: String,
    #[serde(default)]
    pub fecha_envio: Option<String>,
    #[serde(default)]
    pub entrega_estimada: Option<String>,
    #[serde(default)]
    pub fecha_entrega: Option<String>,
    #[serde(default)]
    pub guia: Option<String>,
    pub total_mxn: u32,
    pub ciudad_envio: String,
}

/// Result of resolving a free-form SKU against the catalog.
pub enum SkuResolucion<'a> {
    /// Exact variant SKU (e.g. "VTX-BLK").
    Variante(&'a Product, &'a Variant),
    /// Base product SKU with a single variant — unambiguous.
    ProductoUnico(&'a Product, &'a Variant),
    /// Base product SKU with several variants — caller must disambiguate.
    ProductoAmbiguo(&'a Product),
    /// Nothing matched.
    NoEncontrado,
}

#[derive(Debug, Clone)]
pub struct Catalog {
    pub productos: Vec<Product>,
    pub pedidos: Vec<Order>,
}

impl Catalog {
    pub fn load(productos_path: &Path, pedidos_path: &Path) -> Result<Self> {
        let p = std::fs::read_to_string(productos_path)
            .with_context(|| format!("leyendo catálogo {}", productos_path.display()))?;
        let productos: Vec<Product> = serde_json::from_str(&p)
            .with_context(|| format!("parseando catálogo {}", productos_path.display()))?;

        let o = std::fs::read_to_string(pedidos_path)
            .with_context(|| format!("leyendo pedidos {}", pedidos_path.display()))?;
        let pedidos: Vec<Order> = serde_json::from_str(&o)
            .with_context(|| format!("parseando pedidos {}", pedidos_path.display()))?;

        Ok(Catalog { productos, pedidos })
    }

    pub fn product_by_base_sku(&self, sku: &str) -> Option<&Product> {
        self.productos
            .iter()
            .find(|p| p.sku.eq_ignore_ascii_case(sku))
    }

    pub fn variant_by_sku(&self, sku: &str) -> Option<(&Product, &Variant)> {
        for p in &self.productos {
            if let Some(v) = p.find_variant(sku) {
                return Some((p, v));
            }
        }
        None
    }

    /// Resolve a SKU that may be variant-level or base-level.
    pub fn resolve_sku(&self, sku: &str) -> SkuResolucion<'_> {
        if let Some((p, v)) = self.variant_by_sku(sku) {
            return SkuResolucion::Variante(p, v);
        }
        if let Some(p) = self.product_by_base_sku(sku) {
            return match p.variantes.len() {
                1 => SkuResolucion::ProductoUnico(p, &p.variantes[0]),
                _ => SkuResolucion::ProductoAmbiguo(p),
            };
        }
        SkuResolucion::NoEncontrado
    }

    pub fn order(&self, order_id: &str) -> Option<&Order> {
        let id = normaliza(order_id.trim_start_matches('#'));
        self.pedidos
            .iter()
            .find(|o| normaliza(&o.order_id) == id)
    }
}
